import type { LabelInput } from "@/types/label";

export const emptyLabelInput: LabelInput = {
  productName: "",
  brandName: "",
  productType: "snack",
  servingSize: "",
  servingsPerPackage: 1,
  usuallyConsumedAllAtOnce: false,
  calories: null,
  energyKj: null,
  energyFromFat: null,
  sugar: null,
  sucrose: null,
  lactose: null,
  glucose: null,
  fructose: null,
  maltose: null,
  sodium: null,
  totalFat: null,
  saturatedFat: null,
  transFat: null,
  cholesterol: null,
  protein: null,
  fiber: null,
  carbohydrate: null,
  calcium: null,
  iron: null,
  vitaminA: null,
  vitaminC: null,
  vitaminD: null,
  micronutrients: "",
  ingredients: "",
  allergenText: "",
  claims: "",
};

export const sampleLabelInput: LabelInput = {
  productName: "Minuman Teh Rasa Lemon",
  brandName: "DemoFood",
  productType: "minuman",
  servingSize: "250 ml",
  servingsPerPackage: 1,
  usuallyConsumedAllAtOnce: true,
  calories: 120,
  energyKj: null,
  energyFromFat: null,
  sugar: 24,
  sucrose: null,
  lactose: null,
  glucose: null,
  fructose: null,
  maltose: null,
  sodium: 80,
  totalFat: 0,
  saturatedFat: 0,
  transFat: 0,
  cholesterol: null,
  protein: 0,
  fiber: 0,
  carbohydrate: 30,
  calcium: null,
  iron: null,
  vitaminA: null,
  vitaminC: null,
  vitaminD: null,
  micronutrients: "",
  ingredients: "Air, gula, ekstrak teh, perisa lemon, pengatur keasaman, antioksidan",
  allergenText: "",
  claims: "rasa lemon natural",
};
